# -*- mode: yaml -*-

jobs:
- job: linux
  pool:
    vmImage: ubuntu-16.04
  container:
      image: pdal/ubuntu-dependencies:latest
      options: --privileged
  timeoutInMinutes: 360
  steps:
  - script: |
      mkdir build
      cd build
      cmake .. \
        -G Ninja \
        -DCMAKE_BUILD_TYPE=RelWithDebInfo\
        -DBUILD_PLUGIN_PYTHON=ON \
        -DBUILD_PLUGIN_CPD=ON \
        -DBUILD_PLUGIN_GREYHOUND=ON \
        -DBUILD_PLUGIN_I3S=ON \
        -DBUILD_PLUGIN_NITF=ON \
        -DBUILD_PLUGIN_ICEBRIDGE=ON \
        -DBUILD_PLUGIN_PGPOINTCLOUD=ON \
        -DBUILD_PLUGIN_E57=ON \
        -DBUILD_PGPOINTCLOUD_TESTS=OFF \
        -DPYTHON_EXECUTABLE=/usr/bin/python3 \
        -DBUILD_PLUGIN_SQLITE=ON \
        -DWITH_LASZIP=ON \
        -DWITH_LAZPERF=ON \
        -DWITH_TESTS=ON
    displayName: 'CMake'
  - script: |
      cd build
      ninja
    displayName: 'Build'
  - script: |
      cd build
      export PDAL_PYTHON_LIBRARY=/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu/libpython3.6.so
      ctest -V
    displayName: 'Test'
  - script: |
      export PDAL_TEST_DIR=`pwd`/test
      cd build
      ninja install
      cd /

      # Python extension testing
      pip3 install packaging cython
      git clone https://github.com/PDAL/python.git pdal-python
      cd pdal-python
      git checkout 2.0.0
      python3 setup.py build
      python3 setup.py test
    displayName: 'Python'
  - script: |
      for EXAMPLE in writing writing-filter writing-kernel writing-reader writing-writer
      do
          cd /pdal/examples/$EXAMPLE
          mkdir -p _build || exit 1
          cd _build || exit 1
          cmake -G "Ninja" .. && ninja
      done
    displayName: 'Examples'

